openapi: "3.0.1"
info:
  title: "API Documentation"
  version: "1.0"
paths:
  /api/v1/patients/search/patients:
    get:
      summary: "getAllPatients"
      description: "getAllPatients"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: "string"
                      description: ""
                    name:
                      type: "string"
                      description: ""
                    email:
                      type: "string"
                      description: ""
                    address:
                      type: "string"
                      description: ""
                    dateOfBirth:
                      type: "string"
                      description: ""
  /api/v1/patients/create/patient:
    post:
      summary: "createPatient"
      description: "createPatient"
      requestBody:
        content:
          application/json:
            schema:
              required:
              - "address"
              - "dateOfBirth"
              - "email"
              - "name"
              - "registeredDate"
              type: "object"
              properties:
                name:
                  maxLength: 100
                  type: "string"
                  description: ""
                email:
                  type: "string"
                  description: ""
                  format: "email"
                address:
                  type: "string"
                  description: ""
                dateOfBirth:
                  type: "string"
                  description: ""
                registeredDate:
                  type: "string"
                  description: ""
              description: ""
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                    description: ""
                  name:
                    type: "string"
                    description: ""
                  email:
                    type: "string"
                    description: ""
                  address:
                    type: "string"
                    description: ""
                  dateOfBirth:
                    type: "string"
                    description: ""
  /api/v1/patients/update/{id}/patient:
    put:
      summary: "updatePatient"
      description: "updatePatient"
      parameters:
      - name: "id"
        in: "path"
        description: ""
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              required:
              - "address"
              - "dateOfBirth"
              - "email"
              - "name"
              type: "object"
              properties:
                name:
                  maxLength: 100
                  type: "string"
                  description: ""
                email:
                  type: "string"
                  description: ""
                  format: "email"
                address:
                  type: "string"
                  description: ""
                dateOfBirth:
                  type: "string"
                  description: ""
                registeredDate:
                  type: "string"
                  description: ""
              description: ""
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                    description: ""
                  name:
                    type: "string"
                    description: ""
                  email:
                    type: "string"
                    description: ""
                  address:
                    type: "string"
                    description: ""
                  dateOfBirth:
                    type: "string"
                    description: ""
  /api/v1/patients/delete/{id}/patient:
    delete:
      summary: "deletePatient"
      description: "deletePatient"
      parameters:
      - name: "id"
        in: "path"
        description: ""
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "No Content"
components: {}
